### ISSUE TITLE
Has Prospect lost the ability to plot spectrograph arms separately?

### ISSUE THREAD

**Issue by weaverba137** [desihub/prospect#38] opened 2020-04-24 16:10 UTC
I recently tried plotting data from reference run 19.12 in prospect, and although the spectra came up, when I advanced to the next spectrum, only the blue arm updated, the r and z spectra did not change.  Nor are they properly labeled.  In the rush to plot coadded spectra, did we lose the ability to plot spectrograph arms separately?

To reproduce, use the Prospect_specutils.ipynb notebook, currently on the specutils branch.

**Comment by armengau** [comment] 2020-04-25 13:53
In principle, plotting separate arms should work. However in this case, at least in the current master branch, all three bands 'b' 'r' 'z' are required to be provided.

- I could not run Prospect_specutils.ipynb from the specutils branch: don't know how to import the specutils module itself
- Running my basic prospect sandbox notebook on the mock spectra you provide (single-arm), I cannot reproduce your issue (ie I can use prospect widgets consistently, with 3 arms correctly displayed and updated). This is done with the master prospect branch. Relevant piece of code in notebook:

```
import os, sys
import numpy as np
from astropy.table import Table
import desispec
sys.path.append("/global/homes/a/armengau/prospect/py")
from prospect import utils_specviewer,plotframes

basedir = os.environ['DESI_ROOT']+"/datachallenge/reference_runs/19.12/spectro/redux/mini/spectra-64"
healpixel = '5305'

basedir = basedir + "/" + healpixel[:-2]+"/"+healpixel+"/"
specfile = basedir+'spectra-64-'+healpixel+'.fits'
zbfile = specfile.replace('spectra-64-', 'zbest-64-')
spectra = desispec.io.read_spectra(specfile)
zbest = Table.read(zbfile, 'ZBEST')

print(str(spectra.num_spectra())+" spectra in total")
fm=spectra.fibermap
Nb=10
targets = fm['TARGETID'][0:Nb]
sp_demo = spectra.select(targets=targets)

zcat_demo, kk = utils_specviewer.match_zcat_to_spectra(zbest,sp_demo)

plotframes.plotspectra(sp_demo, zcatalog=zcat_demo, notebook=True, title="sandbox")
```

**Comment by weaverba137** [comment] 2020-04-26 18:52
Thank you for checking.  The problem is on my side then.  I'll dig further.

**Comment by weaverba137** [comment] 2020-04-27 22:34
I found the bug.  [Here](https://github.com/desihub/prospect/blob/d699f45ddb1c48cb4987d2d0abbc83916cd4246e/js/update_plot.js#L227) and [here](https://github.com/desihub/prospect/blob/d699f45ddb1c48cb4987d2d0abbc83916cd4246e/py/prospect/plotframes.py#L632).  `tmp` is undefined.  It should be `var tmp = get_y_minmax(...)`.  The lack of `var` causes execution to stop at that point.

This appears to be due to at least some JavaScript code being declared with `use strict;`.  This may be something that is "helpfully" supplied by bokeh, not a deliberate declaration within the prospect code itself.  The interpretation of `use strict;` may also vary from browser to browser.

**Comment by armengau** [comment] 2020-05-01 13:54
Thanks a lot !
The bug is fixed in the master branch.

**Closed by armengau** 2020-05-01 13:54 UTC
Labels: bug
