### ISSUE TITLE
Plot synchronization issues: "ghost" spectra and arrow/slider sync.

### ISSUE THREAD

**Issue by weaverba137** [desihub/prospect#98] opened 2024-02-20 21:34 UTC
There are several, possibly related synchronization issues that arise when stepping through spectra in Prospect.

1. The spectrum number slider bar is not in sync with the spectrum number indicator immediately next to it.
2. Other sections of the display such as redshift tuning, also do not update, even though targetid, magnitudes, etc, do update.
3. On some spectra, an undesirable "ghost" model spectrum is displayed in a dash line, even though "Best Fit" is the only option ever selected.  This "ghost" model appears to be the best-fit model for a different spectrum, so again, synchronization appears to be a problem.
4. This issue affects both DESI & SDSS/BOSS spectra.

This is best illustrated with three successive screenshots:

1. The first spectrum displayed, spectrum 0:

![Prospect-Screenshot-Spectrum-0](https://github.com/desihub/prospect/assets/3780690/d4449da8-478c-4dce-8529-6db8b744ee80)

2. The second spectrum displayed. Note that the slider bar still says 0, and the redshift adjustment section has not updated. A "ghost" spectrum is visible as a dashed line. Although it's not especially easy to see, the "ghost" appears to actually be the best-fit spectrum from spectrum 0.
 
![Prospect-Screenshot-Spectrum-1](https://github.com/desihub/prospect/assets/3780690/ec54da5f-3d88-4d1b-8562-56014195b8dd)

3. The third spectrum displayed, spectrum 2. Now the slider bar has caught up and the ghost spectrum is absent.

![Prospect-Screenshot-Spectrum-2](https://github.com/desihub/prospect/assets/3780690/9137a5dc-2906-4347-b43e-a711cb213acc)

**Comment by weaverba137** [comment] 2024-02-20 21:49
@armengau, The branch `gui-cosmetics` is now behind main, but it also appears to have very few changes on it. Is there a specific purpose for that branch?

**Comment by weaverba137** [comment] 2024-02-21 00:01
In `ViewerCDS.init_othermodel()`, the "other model" is initialized with the primary model. But there doesn't seem to be a method to change the "other model" to something other than the primary model. Is that just not implemented yet?

**Comment by weaverba137** [comment] 2024-02-21 00:05
PS, the "other model" can be initialized from the standard templates file, but only if `self.cds_othermodel` is not already initialized, but it *is* already initialized in a lot of circumstances.

**Comment by armengau** [comment] 2024-02-26 09:46
> @armengau, The branch `gui-cosmetics` is now behind main, but it also appears to have very few changes on it. Is there a specific purpose for that branch?

This was the last branch merged to the main. Apparently I didn't delete it, I should do it.

**Comment by armengau** [comment] 2024-02-26 09:48
> In `ViewerCDS.init_othermodel()`, the "other model" is initialized with the primary model. But there doesn't seem to be a method to change the "other model" to something other than the primary model. Is that just not implemented yet?

The "other model" is changed by user actions, so this is within the javascript code only.

**Comment by armengau** [comment] 2024-02-26 09:49
This bug you found is scary, I'll try to reproduce and debug it as soon as I can this week.

**Comment by armengau** [comment] 2024-05-02 10:41
I couldn't reproduce a similar problem at this point, neither in standalone html nor in a notebook at nersc (in particular no special error message in javascript). The bokeh version looks the same  ( >>> bokeh.__version__   '2.4.3' ).

From what you get, it looks like there would be a js error when updating the "other model" widget, which would then explain the slider sync issue.

@weaverba137 Can you give me an explicit case (input files and commands), ideally testable at nersc?

**Comment by weaverba137** [comment] 2024-05-02 17:52
I'll specify the full details, but for now, the same notebook at both Data Lab (bokeh==2.3.2) and NERSC (bokeh=2.4.3) give a JavaScript error:
```
TypeError: null is not an object (evaluating 'cds_model_2ndfit.data')
```

**Comment by weaverba137** [comment] 2024-05-02 17:53
Note that I'm providing a model to plotspectra, but not necessarily a *second* model.

**Comment by weaverba137** [comment] 2024-05-02 20:17
I also get the JavaScript error when using the 'Other model (dashed curve):' widget to select 2nd Best model?

I think the recent prospect development has assumed 2nd Best model will always be available.  But if it is *not* available, what happens?

**Closed** 2024-05-03 21:37 UTC
Labels: bug
